# Generated by Django 4.2.5 on 2023-09-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emphub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(to='emphub.project'),
        ),
    ]
